const CONFIG = {
  API_URL: "__API_URL__",
  COGNITO_USER_POOL_ID: "__COGNITO_USER_POOL_ID__",
  COGNITO_CLIENT_ID: "__COGNITO_CLIENT_ID__",
  REGION: "us-east-1",
  S3_BUCKET_NAME: "__S3_BUCKET_NAME__",
  IMAGE_BASE_URL: "__IMAGE_BASE_URL__",
  COGNITO_HOSTED_UI_URL: "__COGNITO_HOSTED_UI_URL__",
  REDIRECT_URL: "__REDIRECT_URL__"
};

export default CONFIG;
